on:
  push:
    branches:
      - main

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Testing"
        echo "Will add code checks here in next challenge"
